backend:
  name: github
  repo: ux-at-icfnext/practice-netlify-cms # Path to your GitHub repository
  netlify.configure({'site_id': gifted-boyd-d36ba9.netlify.com});
  # optional, defaults to master
  # branch: main
media_folder: "assets/img/uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "default"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"

